//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadYoutubeWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadYoutubeWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string BtnClearText {
            get {
                return ResourceManager.GetString("BtnClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example with video.
        /// </summary>
        public static string BtnExampleText1 {
            get {
                return ResourceManager.GetString("BtnExampleText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example with playlist.
        /// </summary>
        public static string BtnExampleText2 {
            get {
                return ResourceManager.GetString("BtnExampleText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load urls.
        /// </summary>
        public static string BtnLoadUrlsMetadataText {
            get {
                return ResourceManager.GetString("BtnLoadUrlsMetadataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download audio in:.
        /// </summary>
        public static string DownloadAudioIn {
            get {
                return ResourceManager.GetString("DownloadAudioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download video in:.
        /// </summary>
        public static string DownloadVideoIn {
            get {
                return ResourceManager.GetString("DownloadVideoIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extraction process of audio and video data of YouTube urls happens in the cloud, so it won’t drain any capacity from your computer..
        /// </summary>
        public static string ExtractionInTheCloudDescription {
            get {
                return ResourceManager.GetString("ExtractionInTheCloudDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction in the cloud.
        /// </summary>
        public static string ExtractionInTheCloudTitle {
            get {
                return ResourceManager.GetString("ExtractionInTheCloudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is being processed. Please wait!.
        /// </summary>
        public static string FileIsBeingProccessed {
            get {
                return ResourceManager.GetString("FileIsBeingProccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and free download of YouTube audio and video files..
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download YouTube audio and video files..
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadYouTube.org app supports the following formats: mp4, webm, mp3, m4a, wma, flac, wav, aac and ogg..
        /// </summary>
        public static string SupportMultipleFormatsDescription {
            get {
                return ResourceManager.GetString("SupportMultipleFormatsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support multiple formats.
        /// </summary>
        public static string SupportMultipleFormatsTitle {
            get {
                return ResourceManager.GetString("SupportMultipleFormatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste YouTube video or playlist urls here..
        /// </summary>
        public static string TbUrlsPlaceholder {
            get {
                return ResourceManager.GetString("TbUrlsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadYouTube.org app runs in the browser, which means it works on all systems. It doesn’t matter If you use Windows, Mac or Linux. Just use a modern Browser!.
        /// </summary>
        public static string WorksOnAllPlatformsDescription {
            get {
                return ResourceManager.GetString("WorksOnAllPlatformsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works on all platforms.
        /// </summary>
        public static string WorksOnAllPlatformsTitle {
            get {
                return ResourceManager.GetString("WorksOnAllPlatformsTitle", resourceCulture);
            }
        }
    }
}
